project_id = "lrpyxyhhqfzozrkklxwu"

[functions.webhook-indicacoes]
verify_jwt = false

[functions.webhook-leads]
verify_jwt = false

[functions.test-sync]
verify_jwt = false

[functions.test-sprinthub-api]
verify_jwt = false

[functions.sync-sprinthub-leads]
verify_jwt = false

[functions.agendamentos-api]
verify_jwt = false

[functions.recalc-weekly-commissions]
verify_jwt = false