project_id = "lrpyxyhhqfzozrkklxwu"

[functions.webhook-leads]
verify_jwt = false

[functions.test-sync]
verify_jwt = false

[functions.test-sprinthub-api]
verify_jwt = false

[functions.sync-sprinthub-leads]
verify_jwt = false